version: '2'

services:

  jupyter-cassandra:
    build:
      context: cassandra-client
      dockerfile: ./Dockerfile.yml
    network_mode: "host"
    ports:
      - 8888:8888
    volumes:
      - ./cassandra-client:/cassandra-client

  cassandra:
    image: 'bitnami/cassandra:3'
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
volumes:
  cassandra_data:
    driver: local
